In [2]:
%reload_ext autoreload
%autoreload 2

import os
import sys
sys.path.append('/Users/forestriveral/Documents/Projects/WFLO')
print(os.getcwd())
import numpy as np

import utils.optimizer as uopt
import miscellaneous.BOA_fuqing as boa


/Users/forestriveral/Documents/Projects/WFLO/debug
|   iter    |  target   |    x1     |    x10    |    x2     |    x3     |    x4     |    x5     |    x6     |    x7     |    x8     |    x9     |
-------------------------------------------------------------------------------------------------------------------------------------------------
|  1        |  6.563    | -19.37    |  0.08968  |  0.1142   | -5.525    |  0.111    |  25.41    |  0.1842   |  5.046    |  0.1781   |  19.11    |
|  2        |  6.889    | -6.688    |  0.2558   |  0.05742  |  25.23    |  0.199    | -23.58    |  0.115    | -26.95    |  0.1534   |  1.439    |
|  3        |  6.351    |  3.715    |  0.1934   |  0.1835   |  25.42    |  0.2457   | -22.98    |  0.2629   | -2.92     |  0.2603   |  9.457    |
|  4        |  6.511    | -7.973    |  0.07861  |  0.1207   | -4.253    |  0.119    | -15.41    |  0.1786   |  10.15    |  0.09838  | -7.832    |
|  5        |  6.335    | -13.54    |  0.07726  |  0.201    | -7.335    |

In [2]:
config = {
        "num": 5,
        "param": "horns",
        "inflow": 8.0,
        "theta": 10.,
        "sector": 3,
        "Iam": 0.077,
        "winds": "horns",
        "wm": "Jensen",
        "wsm": "SS",
        "tim": None,
        "tsm": None,}

In [3]:
layouts = np.array([[800, 3040],
                   [800, 2480],
                   [800, 1920],
                   [800, 1360],
                   [800, 800]])

inputs = np.array([[-10, 0.276],
                   [10, 0.276],
                   [10, 0.152],
                   [10, 0.276],
                   [10, 0.114]])

In [4]:
lp_1 = uopt.LayoutPower(config)
powers_1 = lp_1.yawed_data_generation(layouts, inputs)

powers_1


ytheta: -10.0
wake_offset -45.84610262780443
d_spanwise:  51.39687686567659
r_wake:  62.059693667473454
intersect_ratio: 0.5963491703604674

ytheta: -10.0
wake_offset -66.29317491986632
d_spanwise:  128.19278406709572
r_wake:  84.11938733494691
intersect_ratio: 0.0

ytheta: -10.0
wake_offset -77.87192110937987
d_spanwise:  213.8570173710632
r_wake:  106.17908100242038
intersect_ratio: 0.0

ytheta: -10.0
wake_offset -85.32391489454648
d_spanwise:  303.6480030793775
r_wake:  128.23877466989381
intersect_ratio: 0.0

ytheta: 10.0
wake_offset 45.84610262780443
d_spanwise:  51.39687686567659
r_wake:  62.059693667473454
intersect_ratio: 0.5963491703604674

ytheta: 10.0
wake_offset 66.29317491986632
d_spanwise:  128.19278406709572
r_wake:  84.11938733494692
intersect_ratio: 0.0

ytheta: 10.0
wake_offset 77.87192110937985
d_spanwise:  213.85701737106308
r_wake:  106.17908100242038
intersect_ratio: 0.0

ytheta: 10.0
wake_offset 29.560508790656385
d_spanwise:  67.68247070282463
r_wake:  62.05969

array([1.4566624 , 1.20605513, 1.20605513, 1.37939466, 1.20605513])

In [5]:
layouts = np.array([[800, 3040],
                   [800, 2480],
                   [800, 1920],
                   [800, 1360],
                   [800, 800]])

inputs = np.array([[0, 0.276],
                   [0, 0.276],
                   [0, 0.152],
                   [0, 0.276],
                   [0, 0.114]])

In [6]:
lp_2 = uopt.LayoutPower(config)
powers_2 = lp_2.yawed_data_generation(layouts, inputs)

powers_2


ytheta: 0.0
d_spanwise:  97.24297949348102
r_wake:  62.059693667473454
intersect_ratio: 0.019390294846945617

ytheta: 0.0
d_spanwise:  194.48595898696203
r_wake:  84.11938733494691
intersect_ratio: 0.0

ytheta: 0.0
d_spanwise:  291.72893848044305
r_wake:  106.17908100242038
intersect_ratio: 0.0

ytheta: 0.0
d_spanwise:  388.97191797392395
r_wake:  128.23877466989381
intersect_ratio: 0.0

ytheta: 0.0
d_spanwise:  97.24297949348102
r_wake:  62.059693667473454
intersect_ratio: 0.019390294846945617

ytheta: 0.0
d_spanwise:  194.48595898696203
r_wake:  84.11938733494692
intersect_ratio: 0.0

ytheta: 0.0
d_spanwise:  291.72893848044293
r_wake:  106.17908100242038
intersect_ratio: 0.0

ytheta: 0.0
d_spanwise:  97.24297949348102
r_wake:  62.05969366747347
intersect_ratio: 0.019390294846945672

ytheta: 0.0
d_spanwise:  194.48595898696192
r_wake:  84.11938733494691
intersect_ratio: 0.0

ytheta: 0.0
d_spanwise:  97.2429794934809
r_wake:  62.059693667473454
intersect_ratio: 0.019390294846946238


array([1.4566624 , 1.44901051, 1.44901051, 1.45245309, 1.44901051])

In [4]:
ct = np.array([0.12, 0.8])

ran = (1 - np.sqrt(1 - ct)) / 2
ran

array([0.03095842, 0.2763932 ])

In [27]:
theta = (15 / 360) * (2 * np.pi)
x_D = 0

alpha = np.cos(theta)**2 * np.sin(theta) * 0.4 * (1 + 0.09 * x_D)**-2

print(alpha, alpha / (2 * np.pi) * 360, theta,)

0.09659258262890684 5.534347316905032 0.2617993877991494


In [10]:
np.cos(np.pi / 2)

6.123233995736766e-17

14.758422424179669
21.287129032772203
24.96928107353486
27.333368485684773
14.758422424179669
21.287129032772203
24.96928107353486
14.758422424179669
21.287129032772203
14.758422424179669


array([0.        , 0.10380623, 0.1161396 , 0.12026196, 0.12204329])

In [ ]:
powers = uopt.LayoutPower(config).yawed_data_generation(layouts, inputs)